/**
 * Standardized error codes for the Tide platform
 *
 * Format: DOMAIN_CODE
 * - AUTH: 1000-1999 (Authentication & Authorization)
 * - EMAIL: 2000-2999 (Email operations)
 * - CALENDAR: 3000-3999 (Calendar operations)
 * - AI: 4000-4999 (AI services)
 * - WORKFLOW: 5000-5999 (Workflow & Task operations)
 * - MESSAGE: 6000-6999 (Conversation & Messages)
 * - INTEGRATION: 7000-7999 (External integrations)
 * - DATABASE: 8000-8999 (Database operations)
 * - SYSTEM: 9000-9999 (System & Infrastructure)
 */
export enum ErrorCode {
  // ===== AUTH (1000-1999) =====
  AUTH_INVALID_CREDENTIALS = 'AUTH_1001',
  AUTH_TOKEN_EXPIRED = 'AUTH_1002',
  AUTH_TOKEN_INVALID = 'AUTH_1003',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_1004',
  AUTH_USER_NOT_FOUND = 'AUTH_1005',
  AUTH_USER_ALREADY_EXISTS = 'AUTH_1006',
  AUTH_VERIFICATION_REQUIRED = 'AUTH_1007',
  AUTH_VERIFICATION_TOKEN_INVALID = 'AUTH_1008',
  AUTH_PASSWORD_RESET_REQUIRED = 'AUTH_1009',
  AUTH_SESSION_EXPIRED = 'AUTH_1010',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_1011',
  AUTH_ACCOUNT_LOCKED = 'AUTH_1012',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_1013',

  // ===== EMAIL (2000-2999) =====
  EMAIL_NOT_FOUND = 'EMAIL_2001',
  EMAIL_SEND_FAILED = 'EMAIL_2002',
  EMAIL_FETCH_FAILED = 'EMAIL_2003',
  EMAIL_TRIAGE_FAILED = 'EMAIL_2004',
  EMAIL_DRAFT_FAILED = 'EMAIL_2005',
  EMAIL_INVALID_RECIPIENT = 'EMAIL_2006',
  EMAIL_QUOTA_EXCEEDED = 'EMAIL_2007',
  EMAIL_ATTACHMENT_TOO_LARGE = 'EMAIL_2008',
  EMAIL_PROVIDER_ERROR = 'EMAIL_2009',
  EMAIL_SYNC_FAILED = 'EMAIL_2010',

  // ===== CALENDAR (3000-3999) =====
  CALENDAR_EVENT_NOT_FOUND = 'CALENDAR_3001',
  CALENDAR_EVENT_CONFLICT = 'CALENDAR_3002',
  CALENDAR_PARTICIPANT_UNAVAILABLE = 'CALENDAR_3003',
  CALENDAR_INVALID_TIME_RANGE = 'CALENDAR_3004',
  CALENDAR_SYNC_FAILED = 'CALENDAR_3005',
  CALENDAR_PROVIDER_ERROR = 'CALENDAR_3006',
  CALENDAR_PERMISSION_DENIED = 'CALENDAR_3007',
  CALENDAR_OPTIMIZATION_FAILED = 'CALENDAR_3008',
  CALENDAR_MEETING_PREP_FAILED = 'CALENDAR_3009',

  // ===== AI (4000-4999) =====
  AI_RATE_LIMIT_EXCEEDED = 'AI_4001',
  AI_INVALID_INTENT = 'AI_4002',
  AI_GENERATION_FAILED = 'AI_4003',
  AI_EMBEDDING_FAILED = 'AI_4004',
  AI_PROVIDER_ERROR = 'AI_4005',
  AI_CONTEXT_TOO_LARGE = 'AI_4006',
  AI_INVALID_RESPONSE = 'AI_4007',
  AI_TIMEOUT = 'AI_4008',
  AI_QUOTA_EXCEEDED = 'AI_4009',
  AI_MODEL_NOT_AVAILABLE = 'AI_4010',

  // ===== WORKFLOW (5000-5999) =====
  WORKFLOW_NOT_FOUND = 'WORKFLOW_5001',
  WORKFLOW_EXECUTION_FAILED = 'WORKFLOW_5002',
  WORKFLOW_INVALID_STATE = 'WORKFLOW_5003',
  WORKFLOW_STEP_FAILED = 'WORKFLOW_5004',
  WORKFLOW_TIMEOUT = 'WORKFLOW_5005',
  WORKFLOW_PATTERN_DETECTION_FAILED = 'WORKFLOW_5006',
  WORKFLOW_COMPENSATION_FAILED = 'WORKFLOW_5007',
  TASK_NOT_FOUND = 'WORKFLOW_5010',
  TASK_ALREADY_COMPLETED = 'WORKFLOW_5011',
  TASK_INVALID_STATUS = 'WORKFLOW_5012',

  // ===== MESSAGE (6000-6999) =====
  MESSAGE_NOT_FOUND = 'MESSAGE_6001',
  MESSAGE_SEND_FAILED = 'MESSAGE_6002',
  MESSAGE_INVALID_CONTENT = 'MESSAGE_6003',
  CONVERSATION_NOT_FOUND = 'MESSAGE_6004',
  CONVERSATION_ACCESS_DENIED = 'MESSAGE_6005',
  MESSAGE_TOO_LARGE = 'MESSAGE_6006',
  MESSAGE_RATE_LIMITED = 'MESSAGE_6007',

  // ===== INTEGRATION (7000-7999) =====
  INTEGRATION_OAUTH_FAILED = 'INTEGRATION_7001',
  INTEGRATION_TOKEN_REFRESH_FAILED = 'INTEGRATION_7002',
  INTEGRATION_PROVIDER_UNAVAILABLE = 'INTEGRATION_7003',
  INTEGRATION_SYNC_FAILED = 'INTEGRATION_7004',
  INTEGRATION_WEBHOOK_FAILED = 'INTEGRATION_7005',
  INTEGRATION_API_ERROR = 'INTEGRATION_7006',
  INTEGRATION_RATE_LIMITED = 'INTEGRATION_7007',

  // ===== DATABASE (8000-8999) =====
  DATABASE_CONNECTION_FAILED = 'DATABASE_8001',
  DATABASE_QUERY_FAILED = 'DATABASE_8002',
  DATABASE_TRANSACTION_FAILED = 'DATABASE_8003',
  DATABASE_CONSTRAINT_VIOLATION = 'DATABASE_8004',
  DATABASE_DEADLOCK = 'DATABASE_8005',
  DATABASE_TIMEOUT = 'DATABASE_8006',
  DATABASE_MIGRATION_FAILED = 'DATABASE_8007',
  CACHE_CONNECTION_FAILED = 'DATABASE_8010',
  CACHE_OPERATION_FAILED = 'DATABASE_8011',

  // ===== SYSTEM (9000-9999) =====
  INTERNAL_ERROR = 'SYSTEM_9001',
  SERVICE_UNAVAILABLE = 'SYSTEM_9002',
  SERVICE_TIMEOUT = 'SYSTEM_9003',
  CONFIGURATION_ERROR = 'SYSTEM_9004',
  VALIDATION_FAILED = 'SYSTEM_9005',
  NOT_FOUND = 'SYSTEM_9006',
  BAD_REQUEST = 'SYSTEM_9007',
  FORBIDDEN = 'SYSTEM_9008',
  CONFLICT = 'SYSTEM_9009',
  TOO_MANY_REQUESTS = 'SYSTEM_9010',
  FEATURE_NOT_IMPLEMENTED = 'SYSTEM_9011',
  MAINTENANCE_MODE = 'SYSTEM_9012',
}

/**
 * HTTP status code mapping for error codes
 */
export const ERROR_STATUS_MAP: Record<ErrorCode, number> = {
  // AUTH
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: 403,
  [ErrorCode.AUTH_USER_NOT_FOUND]: 404,
  [ErrorCode.AUTH_USER_ALREADY_EXISTS]: 409,
  [ErrorCode.AUTH_VERIFICATION_REQUIRED]: 403,
  [ErrorCode.AUTH_VERIFICATION_TOKEN_INVALID]: 400,
  [ErrorCode.AUTH_PASSWORD_RESET_REQUIRED]: 403,
  [ErrorCode.AUTH_SESSION_EXPIRED]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 403,
  [ErrorCode.AUTH_ACCOUNT_SUSPENDED]: 403,

  // EMAIL
  [ErrorCode.EMAIL_NOT_FOUND]: 404,
  [ErrorCode.EMAIL_SEND_FAILED]: 500,
  [ErrorCode.EMAIL_FETCH_FAILED]: 500,
  [ErrorCode.EMAIL_TRIAGE_FAILED]: 500,
  [ErrorCode.EMAIL_DRAFT_FAILED]: 500,
  [ErrorCode.EMAIL_INVALID_RECIPIENT]: 400,
  [ErrorCode.EMAIL_QUOTA_EXCEEDED]: 429,
  [ErrorCode.EMAIL_ATTACHMENT_TOO_LARGE]: 413,
  [ErrorCode.EMAIL_PROVIDER_ERROR]: 502,
  [ErrorCode.EMAIL_SYNC_FAILED]: 500,

  // CALENDAR
  [ErrorCode.CALENDAR_EVENT_NOT_FOUND]: 404,
  [ErrorCode.CALENDAR_EVENT_CONFLICT]: 409,
  [ErrorCode.CALENDAR_PARTICIPANT_UNAVAILABLE]: 409,
  [ErrorCode.CALENDAR_INVALID_TIME_RANGE]: 400,
  [ErrorCode.CALENDAR_SYNC_FAILED]: 500,
  [ErrorCode.CALENDAR_PROVIDER_ERROR]: 502,
  [ErrorCode.CALENDAR_PERMISSION_DENIED]: 403,
  [ErrorCode.CALENDAR_OPTIMIZATION_FAILED]: 500,
  [ErrorCode.CALENDAR_MEETING_PREP_FAILED]: 500,

  // AI
  [ErrorCode.AI_RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.AI_INVALID_INTENT]: 400,
  [ErrorCode.AI_GENERATION_FAILED]: 500,
  [ErrorCode.AI_EMBEDDING_FAILED]: 500,
  [ErrorCode.AI_PROVIDER_ERROR]: 502,
  [ErrorCode.AI_CONTEXT_TOO_LARGE]: 413,
  [ErrorCode.AI_INVALID_RESPONSE]: 500,
  [ErrorCode.AI_TIMEOUT]: 504,
  [ErrorCode.AI_QUOTA_EXCEEDED]: 429,
  [ErrorCode.AI_MODEL_NOT_AVAILABLE]: 503,

  // WORKFLOW
  [ErrorCode.WORKFLOW_NOT_FOUND]: 404,
  [ErrorCode.WORKFLOW_EXECUTION_FAILED]: 500,
  [ErrorCode.WORKFLOW_INVALID_STATE]: 400,
  [ErrorCode.WORKFLOW_STEP_FAILED]: 500,
  [ErrorCode.WORKFLOW_TIMEOUT]: 504,
  [ErrorCode.WORKFLOW_PATTERN_DETECTION_FAILED]: 500,
  [ErrorCode.WORKFLOW_COMPENSATION_FAILED]: 500,
  [ErrorCode.TASK_NOT_FOUND]: 404,
  [ErrorCode.TASK_ALREADY_COMPLETED]: 409,
  [ErrorCode.TASK_INVALID_STATUS]: 400,

  // MESSAGE
  [ErrorCode.MESSAGE_NOT_FOUND]: 404,
  [ErrorCode.MESSAGE_SEND_FAILED]: 500,
  [ErrorCode.MESSAGE_INVALID_CONTENT]: 400,
  [ErrorCode.CONVERSATION_NOT_FOUND]: 404,
  [ErrorCode.CONVERSATION_ACCESS_DENIED]: 403,
  [ErrorCode.MESSAGE_TOO_LARGE]: 413,
  [ErrorCode.MESSAGE_RATE_LIMITED]: 429,

  // INTEGRATION
  [ErrorCode.INTEGRATION_OAUTH_FAILED]: 502,
  [ErrorCode.INTEGRATION_TOKEN_REFRESH_FAILED]: 502,
  [ErrorCode.INTEGRATION_PROVIDER_UNAVAILABLE]: 503,
  [ErrorCode.INTEGRATION_SYNC_FAILED]: 500,
  [ErrorCode.INTEGRATION_WEBHOOK_FAILED]: 500,
  [ErrorCode.INTEGRATION_API_ERROR]: 502,
  [ErrorCode.INTEGRATION_RATE_LIMITED]: 429,

  // DATABASE
  [ErrorCode.DATABASE_CONNECTION_FAILED]: 500,
  [ErrorCode.DATABASE_QUERY_FAILED]: 500,
  [ErrorCode.DATABASE_TRANSACTION_FAILED]: 500,
  [ErrorCode.DATABASE_CONSTRAINT_VIOLATION]: 409,
  [ErrorCode.DATABASE_DEADLOCK]: 500,
  [ErrorCode.DATABASE_TIMEOUT]: 504,
  [ErrorCode.DATABASE_MIGRATION_FAILED]: 500,
  [ErrorCode.CACHE_CONNECTION_FAILED]: 500,
  [ErrorCode.CACHE_OPERATION_FAILED]: 500,

  // SYSTEM
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.SERVICE_TIMEOUT]: 504,
  [ErrorCode.CONFIGURATION_ERROR]: 500,
  [ErrorCode.VALIDATION_FAILED]: 400,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.TOO_MANY_REQUESTS]: 429,
  [ErrorCode.FEATURE_NOT_IMPLEMENTED]: 501,
  [ErrorCode.MAINTENANCE_MODE]: 503,
};
