[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["cd ../../.. && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd ../../.. && pnpm --filter @tide/calendar-service build"]

[start]
cmd = "cd packages/services/calendar && node dist/index.js"
