import { logger } from '@tide/logger';
import { UserId } from '@tide/types';
import {
  Task,
  TaskId,
  TaskRequest,
  TaskStatus,
  Subtask,
  TaskPriority,
  TaskDependency,
} from '../types/task.types';
import { TaskRepository } from '../persistence/task-repository';

/**
 * Task Management Engine
 *
 * Intelligent task engine with smart prioritization, auto-decomposition,
 * and dependency management
 */
export class TaskEngine {
  constructor(
    private repository: TaskRepository,
    private prioritizer: TaskPrioritizer,
    private decomposer: TaskDecomposer
  ) {}

  /**
   * Create a new task with smart defaults
   */
  async createTask(request: TaskRequest): Promise<Task> {
    // Calculate priority
    const priority = await this.prioritizer.calculate(request);

    // Assess complexity
    const complexity = await this.assessComplexity(request);

    // Estimate duration
    const estimatedDuration = await this.estimateTime(request);

    // Auto-tag
    const tags = await this.autoTag(request);

    // Create task
    const task: Task = {
      id: this.generateId() as TaskId,
      userId: request.userId,
      title: request.title,
      description: request.description,
      priority,
      dueDate: request.dueDate,
      estimatedDuration,
      assignee: request.assignee,
      tags,
      project: request.project,
      status: 'pending',
      progress: 0,
      complexity,
      metadata: {
        source: 'user',
        autoGenerated: false,
        ...request.metadata,
      },
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    // Save task
    await this.repository.createTask(task);

    // Break down into subtasks if complex
    if (complexity && complexity > 0.7) {
      await this.decomposeTask(task);
    }

    // Set up dependencies
    if (request.dependencies) {
      for (const depId of request.dependencies) {
        await this.repository.addDependency({
          taskId: task.id,
          dependsOnTaskId: depId as TaskId,
          type: 'blocks',
        });
      }
    }

    logger.info({ taskId: task.id, priority, complexity }, 'Task created');

    return task;
  }

  /**
   * Decompose complex task into subtasks
   */
  private async decomposeTask(task: Task): Promise<Subtask[]> {
    const subtasks = await this.decomposer.decompose(task);

    for (const subtask of subtasks) {
      await this.repository.createSubtask(subtask);
    }

    logger.info({ taskId: task.id, subtaskCount: subtasks.length }, 'Task decomposed');

    return subtasks;
  }

  /**
   * Get ready tasks (no blocking dependencies)
   */
  async getReadyTasks(userId: UserId): Promise<Task[]> {
    const tasks = await this.repository.getReadyTasks(userId);

    // Sort by priority
    const prioritized = await this.prioritizer.order(tasks);

    return prioritized;
  }

  /**
   * Execute tasks in priority order
   */
  async executeTasks(userId: UserId): Promise<ExecutionReport> {
    const readyTasks = await this.getReadyTasks(userId);
    const results: TaskResult[] = [];

    for (const task of readyTasks) {
      // Check if still relevant
      if (await this.isStillRelevant(task)) {
        // Mark as in progress
        task.status = 'in_progress';
        task.startedAt = new Date();
        await this.repository.updateTask(task);

        // Execute task (placeholder - actual execution would be service-specific)
        const result: TaskResult = {
          taskId: task.id,
          success: true,
          completedAt: new Date(),
        };

        // Update task status
        task.status = 'completed';
        task.progress = 100;
        task.completedAt = new Date();
        await this.repository.updateTask(task);

        results.push(result);

        // Notify dependent tasks
        await this.notifyDependentTasks(task.id);
      }
    }

    return {
      executed: results.filter(r => r.success),
      failed: results.filter(r => !r.success),
      skipped: readyTasks.length - results.length,
    };
  }

  /**
   * Update task priority dynamically
   */
  async updateTaskPriority(taskId: TaskId): Promise<number> {
    const task = await this.repository.getTask(taskId);
    if (!task) {
      throw new Error(`Task not found: ${taskId}`);
    }

    const newPriority = await this.prioritizer.calculateDynamicPriority(task);

    task.priority = newPriority;
    task.updatedAt = new Date();
    await this.repository.updateTask(task);

    return newPriority;
  }

  /**
   * Check if task is still relevant
   */
  private async isStillRelevant(task: Task): Promise<boolean> {
    // Check if not already completed
    if (task.status === 'completed' || task.status === 'cancelled') {
      return false;
    }

    // Check if past due (might want to skip or reprioritize)
    if (task.dueDate && task.dueDate < new Date()) {
      // Still relevant but overdue
      return true;
    }

    return true;
  }

  /**
   * Notify tasks that depend on completed task
   */
  private async notifyDependentTasks(taskId: TaskId): Promise<void> {
    const dependentTaskIds = await this.repository.getDependentTasks(taskId);

    for (const depTaskId of dependentTaskIds) {
      // Recalculate priority since dependency is now resolved
      await this.updateTaskPriority(depTaskId);
    }
  }

  /**
   * Assess task complexity
   */
  private async assessComplexity(request: TaskRequest): Promise<number> {
    let complexity = 0.5; // Base complexity

    // Increase complexity based on description length
    if (request.description) {
      const words = request.description.split(' ').length;
      if (words > 100) complexity += 0.2;
      else if (words > 50) complexity += 0.1;
    }

    // Increase complexity if has dependencies
    if (request.dependencies && request.dependencies.length > 0) {
      complexity += request.dependencies.length * 0.05;
    }

    // Increase complexity if multi-step (detected by keywords)
    const multiStepKeywords = ['first', 'then', 'after', 'finally', 'step'];
    const description = (request.title + ' ' + (request.description || '')).toLowerCase();
    const matchCount = multiStepKeywords.filter(kw => description.includes(kw)).length;
    if (matchCount > 0) {
      complexity += matchCount * 0.1;
    }

    return Math.min(complexity, 1.0);
  }

  /**
   * Estimate task duration
   */
  private async estimateTime(request: TaskRequest): Promise<number> {
    // Simple estimation based on complexity
    const complexity = await this.assessComplexity(request);

    // Base time: 30 minutes
    // Complex tasks: up to 4 hours
    return Math.round(30 + (complexity * 210)); // 30 + (0-210 minutes)
  }

  /**
   * Auto-tag task based on content
   */
  private async autoTag(request: TaskRequest): Promise<string[]> {
    const tags: string[] = request.tags || [];
    const content = (request.title + ' ' + (request.description || '')).toLowerCase();

    // Common keywords
    const tagMap: Record<string, string> = {
      'urgent': 'urgent',
      'important': 'important',
      'meeting': 'meeting',
      'email': 'email',
      'review': 'review',
      'research': 'research',
      'bug': 'bug',
      'feature': 'feature',
      'documentation': 'docs',
      'test': 'testing',
    };

    for (const [keyword, tag] of Object.entries(tagMap)) {
      if (content.includes(keyword) && !tags.includes(tag)) {
        tags.push(tag);
      }
    }

    return tags;
  }

  /**
   * Generate ID
   */
  private generateId(): string {
    return `task_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }
}

/**
 * Task Prioritizer
 *
 * Implements smart priority calculation using multiple factors
 */
export class TaskPrioritizer {
  /**
   * Calculate initial priority for new task
   */
  async calculate(request: TaskRequest): Promise<number> {
    const factors: TaskPriority = {
      urgency: await this.calculateUrgency(request),
      importance: await this.calculateImportance(request),
      impact: await this.calculateImpact(request),
      effort: await this.calculateEffort(request),
      dependencies: await this.calculateDependencyScore(request),
    };

    // Weighted average (Eisenhower Matrix + enhancements)
    const score =
      factors.urgency * 0.3 +
      factors.importance * 0.3 +
      factors.impact * 0.2 +
      (1 - factors.effort) * 0.1 + // Lower effort = higher priority
      factors.dependencies * 0.1;

    return Math.min(Math.max(score, 0), 1.0);
  }

  /**
   * Calculate dynamic priority (adjusts over time)
   */
  async calculateDynamicPriority(task: Task): Promise<number> {
    let priority = task.priority;

    // Adjust for time sensitivity
    if (task.dueDate) {
      const hoursUntilDue = (task.dueDate.getTime() - Date.now()) / 3600000;
      if (hoursUntilDue < 24) priority += 0.3;
      else if (hoursUntilDue < 72) priority += 0.1;
    }

    // Adjust for age (older tasks get higher priority)
    const ageInDays = (Date.now() - task.createdAt.getTime()) / 86400000;
    if (ageInDays > 7) priority += 0.1;
    if (ageInDays > 30) priority += 0.2;

    return Math.min(priority, 1.0);
  }

  /**
   * Order tasks by priority
   */
  async order(tasks: Task[]): Promise<Task[]> {
    // Calculate dynamic priorities
    const scored = await Promise.all(
      tasks.map(async task => ({
        task,
        score: await this.calculateDynamicPriority(task),
      }))
    );

    // Sort by score descending
    return scored
      .sort((a, b) => b.score - a.score)
      .map(item => item.task);
  }

  /**
   * Calculate urgency (time-based)
   */
  private async calculateUrgency(request: TaskRequest): Promise<number> {
    if (!request.dueDate) return 0.5;

    const hoursUntilDue = (request.dueDate.getTime() - Date.now()) / 3600000;

    if (hoursUntilDue < 0) return 1.0; // Overdue
    if (hoursUntilDue < 24) return 0.9;
    if (hoursUntilDue < 72) return 0.7;
    if (hoursUntilDue < 168) return 0.5; // 1 week
    return 0.3;
  }

  /**
   * Calculate importance (impact-based)
   */
  private async calculateImportance(request: TaskRequest): Promise<number> {
    let importance = 0.5;

    // Check tags for importance indicators
    const importanceTags = ['urgent', 'important', 'critical', 'high-priority'];
    const tags = request.tags || [];
    if (tags.some(tag => importanceTags.includes(tag.toLowerCase()))) {
      importance = 0.9;
    }

    return importance;
  }

  /**
   * Calculate impact
   */
  private async calculateImpact(request: TaskRequest): Promise<number> {
    // Simple heuristic: longer description = higher impact
    const descriptionLength = request.description?.length || 0;
    return Math.min(descriptionLength / 500, 1.0);
  }

  /**
   * Calculate effort (inverse priority - lower effort = higher priority)
   */
  private async calculateEffort(request: TaskRequest): Promise<number> {
    // Estimate effort from description
    const words = (request.description || '').split(' ').length;

    if (words < 10) return 0.2; // Low effort
    if (words < 50) return 0.5; // Medium effort
    return 0.8; // High effort
  }

  /**
   * Calculate dependency score
   */
  private async calculateDependencyScore(request: TaskRequest): Promise<number> {
    const depCount = request.dependencies?.length || 0;
    return Math.min(depCount * 0.2, 1.0);
  }
}

/**
 * Task Decomposer
 *
 * Breaks down complex tasks into smaller subtasks
 */
export class TaskDecomposer {
  /**
   * Decompose task into subtasks
   */
  async decompose(task: Task): Promise<Subtask[]> {
    const subtasks: Subtask[] = [];

    // Simple decomposition based on description
    // In production, this would use AI
    const steps = this.extractSteps(task.description || task.title);

    for (let i = 0; i < steps.length; i++) {
      const subtask: Subtask = {
        id: `${task.id}_sub_${i}` as any,
        parentId: task.id,
        title: steps[i],
        order: i,
        estimatedTime: Math.round((task.estimatedDuration || 60) / steps.length),
        status: 'pending',
        createdAt: new Date(),
        updatedAt: new Date(),
      };

      subtasks.push(subtask);
    }

    return subtasks;
  }

  /**
   * Extract steps from description
   */
  private extractSteps(text: string): string[] {
    // Look for numbered lists or step keywords
    const steps: string[] = [];

    // Match numbered lists: "1. ", "2. ", etc.
    const numberedPattern = /\d+\.\s+([^\n]+)/g;
    let match;
    while ((match = numberedPattern.exec(text)) !== null) {
      steps.push(match[1].trim());
    }

    // If no numbered list, split by keywords
    if (steps.length === 0) {
      const keywords = ['first', 'then', 'next', 'after that', 'finally'];
      for (const keyword of keywords) {
        const regex = new RegExp(`${keyword}[,:]?\\s+([^.!?]+)`, 'gi');
        while ((match = regex.exec(text)) !== null) {
          steps.push(match[1].trim());
        }
      }
    }

    // If still no steps, create default breakdown
    if (steps.length === 0) {
      steps.push('Research and planning');
      steps.push('Implementation');
      steps.push('Testing and review');
    }

    return steps;
  }
}

// Types
export interface TaskResult {
  taskId: TaskId;
  success: boolean;
  error?: string;
  completedAt: Date;
}

export interface ExecutionReport {
  executed: TaskResult[];
  failed: TaskResult[];
  skipped: number;
}
